### ISSUE TITLE
Q: How can I refer to facet restrictions in OWL class expression?

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#142]
I am currently trying to define this is my template for equivalent class expression:

```
equivalentTo:
  text: "('inheres_in' some ('population of Drosophila' and ('has_member' some ('multicellular organism' and (has_age some ('preceded_by' some %s)))) and ('has_member' only ('multicellular organism' and (has_age some ('preceded_by' some %s)))))) and ('has_increased_mortality_rate' some xsd:short[>= 98])"
  vars:
    - stage
    - stage
```

Which results in this parse error:

```
Exception in thread "main" org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered [ at line 1 column 301. Expected one of:
	or
	and
	)

	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl$ExceptionBuilder.build(ManchesterOWLSyntaxParserImpl.java:2519)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNestedClassExpression(ManchesterOWLSyntaxParserImpl.java:1076)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNonNaryClassExpression(ManchesterOWLSyntaxParserImpl.java:704)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseIntersection(ManchesterOWLSyntaxParserImpl.java:604)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseUnion(ManchesterOWLSyntaxParserImpl.java:627)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseClassExpression(ManchesterOWLSyntaxParserImpl.java:586)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxClassExpressionParser.parse(ManchesterOWLSyntaxClassExpressionParser.java:61)
	at org.monarchinitiative.dosdp.ExpandedDOSDP.expressionFor(ExpandedDOSDP.scala:69)
```

If I drop the last restriction, it works, so I assume it has something to do with the datatype facet syntax.. Any idea @balhoff ?

**Comment by dosumis** [comment]
As this works in Protege, I wonder whether it's down to limitations in expressiveness OWL-API MS parse vs the one used by Protege?  IIRC, Protege implements some extensions to MS to deal with missing exressiveness in W3C MS spec.
