### ISSUE TITLE
Labels not properly rendering

### ISSUE THREAD

**Issue by austinmeier** [INCATools/dosdp-tools#17]
Using this tool, the labels are not properly being recognized by dosdp-tools.  Instead of pulling the label for each instance, it is leaving it as a purl (instead of "insecticide", it shows "http://purl.obolibrary.org/obo/CHEBI_24852")

see our repo: https://github.com/Planteome/plant-environment-ontology/tree/master/patterns

cc: @cmungall @mariealaporte

**Comment by balhoff** [comment]
I will try it out tomorrow, but I think you need to add two sections to your pattern:

```yaml
annotationProperties:
  label: rdfs:label

readable_identifiers:
  - label
```

My tool may be more strict about this than David's was. @dosumis should I be providing implicit defaults for this?

I don't think I've tested my implementation of this yet, so I may find something to fix tomorrow.

**Comment by balhoff** [comment]
I just tried to run it with those sections added to the yaml, and it seems to work (assuming you're passing it an ontology containing the needed label axioms).

**Comment by austinmeier** [comment]
I tried this morning using this exactly:

```
pattern_name: eo
classes:
  plant experimental condition: EO:0007359
  plant treatment: EO:0001001
  exposure event: RO:0002310

relations:
  contains: RO:0001019
  has exposure stimulus: RO:0002244
  has participant: RO:0000057
    
annotationProperties:
  label: rdfs:label

readable_identifiers:
  - label

vars: 
  stimulus: "'Thing'"

name:
  text: "%s treatment"
  vars:
    - stimulus
    
def: 
  text: "A treatment involving the use of %s"
  vars:
    - stimulus
    
equivalentTo: 
  text: "'plant treatment' and 'has exposure stimulus' some %s"
  vars:
    - stimulus
```


And received this error:  `Exception in thread "main" java.lang.NullPointerException`


I have also modified the `eo.tsv` to modify the headers to `stimulus` and `stimulus_label`  did you also do that before running dosdp-tools?

**Comment by balhoff** [comment]
Yes, you do need the headers to match the variables. Are you using the `--obo-prefixes` option? This will automatically define `rdfs:` in case that is the problem.

Can you paste the rest of the stack trace that comes after `Exception in thread "main" java.lang.NullPointerException`?

Thanks. I'll try to use these problems to improve the error reporting.

**Comment by austinmeier** [comment]
Just for clarity, we are trying to generate an owl file using a yaml pattern, and a tsv of terms.  The exact command I am using is:

`dosdp-tools/target/universal/stage/bin/dosdp-tools --outfile=eo_pattern.owl --prefixes=curie_map.yaml --template=eo.yaml generate --infile=eo.tsv`

So I was not using the `--obo-prefixes` option.

The whole stack trace is as follows:  

```
Exception in thread "main" java.lang.NullPointerException
	at org.monarchinitiative.dosdp.cli.Generate$$anonfun$1.applyOrElse(Generate.scala:104)
	at org.monarchinitiative.dosdp.cli.Generate$$anonfun$1.applyOrElse(Generate.scala:103)
	at scala.collection.TraversableOnce$class.collectFirst(TraversableOnce.scala:145)
	at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:104)
	at org.monarchinitiative.dosdp.cli.Generate$.org$monarchinitiative$dosdp$cli$Generate$$readableIdentifierForIRI(Generate.scala:103)
	at org.monarchinitiative.dosdp.cli.Generate$$anonfun$org$monarchinitiative$dosdp$cli$Generate$$irisToLabels$1.apply(Generate.scala:98)
	at org.monarchinitiative.dosdp.cli.Generate$$anonfun$org$monarchinitiative$dosdp$cli$Generate$$irisToLabels$1.apply(Generate.scala:98)
	at scala.Option.map(Option.scala:146)
	at org.monarchinitiative.dosdp.cli.Generate$.org$monarchinitiative$dosdp$cli$Generate$$irisToLabels(Generate.scala:98)
	at org.monarchinitiative.dosdp.cli.Generate$$anonfun$4$$anonfun$9.apply(Generate.scala:74)
	at org.monarchinitiative.dosdp.cli.Generate$$anonfun$4$$anonfun$9.apply(Generate.scala:74)
	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:245)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.MapBuilder.$plus$plus$eq(MapBuilder.scala:25)
	at scala.collection.immutable.DefaultMap$class.$plus(DefaultMap.scala:40)
	at scala.collection.immutable.MapLike$$anon$2.$plus(MapLike.scala:102)
	at org.monarchinitiative.dosdp.cli.Generate$$anonfun$4.apply(Generate.scala:77)
	at org.monarchinitiative.dosdp.cli.Generate$$anonfun$4.apply(Generate.scala:50)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:20)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toSet(TraversableOnce.scala:304)
	at scala.collection.AbstractIterator.toSet(Iterator.scala:1336)
	at org.monarchinitiative.dosdp.cli.Generate$.run(Generate.scala:80)
	at org.monarchinitiative.dosdp.cli.Main$$anonfun$1.apply(Main.scala:32)
	at org.monarchinitiative.dosdp.cli.Main$$anonfun$1.apply(Main.scala:32)
	at scala.Option.foreach(Option.scala:257)
	at org.monarchinitiative.dosdp.cli.Main$.delayedEndpoint$org$monarchinitiative$dosdp$cli$Main$1(Main.scala:32)
	at org.monarchinitiative.dosdp.cli.Main$delayedInit$body.apply(Main.scala:29)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.monarchinitiative.dosdp.cli.Main$.main(Main.scala:29)
	at org.monarchinitiative.dosdp.cli.Main.main(Main.scala)
```

**Comment by balhoff** [comment]
`--obo-prefixes=true` will predefine prefixes for `rdf`, `rdfs`, and `owl`, and expand all other CURIEs into OBO IRIs. For your case you could probably use this instead of `--prefixes=curie_map.yaml`. But you can use them in combination and prefixes in your file will take precedence. When I tried running without defining `rdfs` I got the same error you saw.

**Comment by austinmeier** [comment]
adding `--obo-prefixes=true` did in-fact resolve the `NullPointerException`, however the label is still not being recognized.  The resulting .owl file continues to be populated with terms who's label is "x_treatment" where x is a URL (eg:"http://purl.obolibrary.org/obo/CHEBI_24852") instead of the actual label.

Is it possible for you to provide a working example of a .yaml pattern, and .tsv?

I appreciate the help in getting this to work.

**Comment by balhoff** [comment]
Oh I think I see what's missing. You aren't passing an ontology with `--ontology`. Annotation axioms in the ontology are searched to get the labels. You would need one that had all the labels for the terms in your TSV. It occurs to me that the tool could instead grab whatever label is in the input TSV, but that isn't how the spec is currently defined. You can give a list of annotation properties in order of preference, and it will search the ontology with all of them.

**Comment by austinmeier** [comment]
Ahhhhhhhh!!! Jackpot!  That is exactly the issue.  Adding `--ontology=` argument has corrected the CHEBI_ID issue.  But this leads me to my next issue:  Can I pass in multiple ontologies in the `--ontology` option?  I tried passing the option twice; that didn't work, and I also passed with the option `--ontology=./ontology1.owl ./ontology2.owl` and that also didn't work.  Is this possible, or will I need to merge my input ontologies into a single .owl?

Thanks again!

**Comment by balhoff** [comment]
You can either merge them or import them in a new ontology (but then OWL API would need to be able to find the imported ontologies via the web).

**Comment by austinmeier** [comment]
Excellent.  Thank you again.  In the future will it be possible to import the label directly from the .tsv file?  If this functionality mirrors that of @cmungall 's [`apply-pattern.py`](https://github.com/cmungall/pattern2owl) it will simplify the release process that was made standard by the [ontology-startup-kit](https://github.com/cmungall/ontology-starter-kit)

**Comment by balhoff** [comment]
Glad it's working! I'll see what @cmungall and @dosumis think about getting "readable identifiers" from the TSV. Seems good to me, and it could at least be a fallback.

**Comment by austinmeier** [comment]
Great.  We discussed this at the GOC this weekend, and think that would be a valuable option for ontologies that are maintained/edited directly in the .tsv.  Feel free to close this issue, unless you want to keep it open for discussion about "readable identifiers"

**Comment by cmungall** [comment]
Either way I think we need something to 'refresh' the labels in the tsv. This needn't be part of dosdp-tools, it's just a straightforward lookup and replace.

**Comment by dosumis** [comment]
Sorry for not pitching in on this earlier.  

The readable_identifier is meant to be set to rdfs:label for the OBO extension.  This is in the [paper](https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-017-0126-0): 

"we define an extension to support the OBO standard. This defines convenience fields for expressing OBO standard annotations and specifies a default annotation property for readable identifiers..."

My plan to support his was via a YAML file with pre-filled default properties:
https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/spec/OBO_import.yml

**Comment by balhoff** [comment]
As of 7d49830915d249f44a8edf43bdfa743b61126f60 labels in the input TSV override lookups in the ontology.
