### ISSUE TITLE
0.14 Beta fails to read Manchester Syntax

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#199]
This error looks like it is caused by Manchester syntax reading, but I verified that it did not (0.13 works normally). Could it be that the 'optionality' introduced for all vars actually causes this failure, i.e. to prevent DOSDP tools from swapping in somehow the filler variable into the manchester syntax strings?

```
Encountered '' at line 1 column 108. Expected one of:
	Class name
	(
	{
	Self

Exception in thread "main" org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered '' at line 1 column 108. Expected one of:
	Class name
	(
	{
	Self

	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl$ExceptionBuilder.build(ManchesterOWLSyntaxParserImpl.java:2562)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNestedClassExpression(ManchesterOWLSyntaxParserImpl.java:1130)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseObjectRestriction(ManchesterOWLSyntaxParserImpl.java:756)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNonNaryClassExpression(ManchesterOWLSyntaxParserImpl.java:728)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseIntersection(ManchesterOWLSyntaxParserImpl.java:611)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseUnion(ManchesterOWLSyntaxParserImpl.java:634)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNestedClassExpression(ManchesterOWLSyntaxParserImpl.java:1103)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNonNaryClassExpression(ManchesterOWLSyntaxParserImpl.java:735)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseIntersection(ManchesterOWLSyntaxParserImpl.java:611)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseUnion(ManchesterOWLSyntaxParserImpl.java:634)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNestedClassExpression(ManchesterOWLSyntaxParserImpl.java:1103)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseObjectRestriction(ManchesterOWLSyntaxParserImpl.java:756)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNonNaryClassExpression(ManchesterOWLSyntaxParserImpl.java:728)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseIntersection(ManchesterOWLSyntaxParserImpl.java:611)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseUnion(ManchesterOWLSyntaxParserImpl.java:634)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseClassExpression(ManchesterOWLSyntaxParserImpl.java:593)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxClassExpressionParser.parse(ManchesterOWLSyntaxClassExpressionParser.java:61)
	at org.monarchinitiative.dosdp.ExpandedDOSDP.$anonfun$expressionFor$1(ExpandedDOSDP.scala:81)
	at scala.Option.map(Option.scala:230)
	at org.monarchinitiative.dosdp.ExpandedDOSDP.expressionFor(ExpandedDOSDP.scala:81)
	at org.monarchinitiative.dosdp.ExpandedDOSDP.$anonfun$equivalentToExpression$1(ExpandedDOSDP.scala:30)
	at scala.Option.flatMap(Option.scala:271)
	at org.monarchinitiative.dosdp.ExpandedDOSDP.equivalentToExpression(ExpandedDOSDP.scala:29)
	at org.monarchinitiative.dosdp.ExpandedDOSDP.filledLogicalAxioms(ExpandedDOSDP.scala:69)
	at org.monarchinitiative.dosdp.cli.Generate$.$anonfun$renderPattern$5(Generate.scala:135)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:24)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
	at scala.collection.AbstractIterator.to(Iterator.scala:1429)
	at scala.collection.TraversableOnce.toSet(TraversableOnce.scala:309)
	at scala.collection.TraversableOnce.toSet$(TraversableOnce.scala:309)
	at scala.collection.AbstractIterator.toSet(Iterator.scala:1429)
	at org.monarchinitiative.dosdp.cli.Generate$.renderPattern(Generate.scala:82)
	at org.monarchinitiative.dosdp.cli.Generate$.renderPattern(Generate.scala:73)
	at org.monarchinitiative.dosdp.cli.Prototype$.$anonfun$axiomsFor$1(Prototype.scala:42)
	at scala.Option.map(Option.scala:230)
	at org.monarchinitiative.dosdp.cli.Prototype$.axiomsFor(Prototype.scala:36)
	at org.monarchinitiative.dosdp.cli.Prototype$.$anonfun$run$5(Prototype.scala:28)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:132)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.monarchinitiative.dosdp.cli.Prototype$.run(Prototype.scala:27)
	at org.monarchinitiative.dosdp.cli.Main$.$anonfun$new$1(Main.scala:10)
	at org.monarchinitiative.dosdp.cli.Main$.$anonfun$new$1$adapted(Main.scala:10)
	at scala.Option.foreach(Option.scala:407)
	at org.monarchinitiative.dosdp.cli.Main$.delayedEndpoint$org$monarchinitiative$dosdp$cli$Main$1(Main.scala:10)
	at org.monarchinitiative.dosdp.cli.Main$delayedInit$body.apply(Main.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at org.monarchinitiative.dosdp.cli.Main$.main(Main.scala:6)
	at org.monarchinitiative.dosdp.cli.Main.main(Main.scala)
Makefile:485: recipe for target '../patterns/pattern.owl' failed
```

**Comment by balhoff** [comment]
It looks like you're running `prototype`, right? Can you send me the pattern?

**Comment by matentzn** [comment]
you can checkout upheno and replicate the src/ontology/Makefile command for `pattern_ontology`; that is the command I ran! :)
