### ISSUE TITLE
DOSPT batch mode should have a nice message when pattern is missing

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#207]
Currently if a pattern is added in batch mode --batch-patterns="a b", we get a somewhat cryptic failure:

```
Exception in thread "main" java.net.MalformedURLException: no protocol: ../patterns/a.yaml
	at java.net.URL.<init>(URL.java:611)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at scala.io.Source$.fromURL(Source.scala:134)
```

Maybe this can be improved easily.

**Comment by jdr0887** [comment]
After the ZIO changes by @balhoff, the error message reads: 

```
org.monarchinitiative.dosdp.cli.DOSDPError: Could not read pattern file at ../patterns/dosdp-patterns/a.yaml                                                                                                                                                  
        at org.monarchinitiative.dosdp.cli.Config$.$anonfun$inputDOSDPFrom$11(Config.scala:162)                                                                                                                                                               
        at zio.Cause.$anonfun$map$1(Cause.scala:237)                                                                                                                                                                                                          
        at zio.Cause.flatMap(Cause.scala:124)                      
```

This error message seems to be thrown at the time that each file is intended to be used/read.  Were you hoping for a fail fast exception to be thrown before any processing is done?  If not, then I would argue that the message is less cryptic and this issue can be closed.

**Comment by matentzn** [comment]
Totally happy with that message, no need for anything else!
