### ISSUE TITLE
Error messages can be obscure

### ISSUE THREAD

**Issue by cmungall** [INCATools/dosdp-tools#23]
E.g.
https://build.berkeleybop.org/job/query-go-patterns/10/console

```
17:21:19.363 [main] DEBUG org.semanticweb.owlapi.rdf.rdfxml.parser.TripleLogger - Loaded OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/go.owl>) VersionIRI(<null>))
log4j:WARN No appenders could be found for logger (org.semanticweb.elk.config.ConfigurationFactory).
log4j:WARN Please initialize the log4j system properly.
Exception in thread "main" org.apache.jena.query.QueryParseException: Line 15, column 121: Unresolved prefixed name: http:
	at org.apache.jena.sparql.lang.ParserBase.throwParseException(ParserBase.java:521)
	at org.apache.jena.sparql.lang.ParserBase.resolvePName(ParserBase.java:286)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.PrefixedName(SPARQLParser11.java:4861)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.iri(SPARQLParser11.java:4841)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.RDFLiteral(SPARQLParser11.java:4673)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.GraphTerm(SPARQLParser11.java:3367)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.VarOrTerm(SPARQLParser11.java:3277)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.GraphNodePath(SPARQLParser11.java:3233)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.ObjectPath(SPARQLParser11.java:2749)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.ObjectListPath(SPARQLParser11.java:2730)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.PropertyListPathNotEmpty(SPARQLParser11.java:2663)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesSameSubjectPath(SPARQLParser11.java:2607)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesBlock(SPARQLParser11.java:1792)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.GroupGraphPatternSub(SPARQLParser11.java:1775)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.GroupGraphPattern(SPARQLParser11.java:1675)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.WhereClause(SPARQLParser11.java:431)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.SelectQuery(SPARQLParser11.java:124)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.Query(SPARQLParser11.java:29)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.QueryUnit(SPARQLParser11.java:20)
	at org.apache.jena.sparql.lang.ParserSPARQL11$1.exec(ParserSPARQL11.java:48)
	at org.apache.jena.sparql.lang.ParserSPARQL11.perform(ParserSPARQL11.java:96)
	at org.apache.jena.sparql.lang.ParserSPARQL11.parse$(ParserSPARQL11.java:52)
	at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
	at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:52)
	at org.apache.jena.query.QueryFactory.create(QueryFactory.java:40)
	at org.phenoscape.owlet.Owlet.expandQueryString(Owlet.scala:56)
	at org.monarchinitiative.dosdp.cli.Query$.run(Query.scala:42)
	at org.monarchinitiative.dosdp.cli.Main$$anonfun$1.apply(Main.scala:32)
	at org.monarchinitiative.dosdp.cli.Main$$anonfun$1.apply(Main.scala:32)
	at scala.Option.foreach(Option.scala:257)
	at org.monarchinitiative.dosdp.cli.Main$.delayedEndpoint$org$monarchinitiative$dosdp$cli$Main$1(Main.scala:32)
	at org.monarchinitiative.dosdp.cli.Main$delayedInit$body.apply(Main.scala:29)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.monarchinitiative.dosdp.cli.Main$.main(Main.scala:29)
	at org.monarchinitiative.dosdp.cli.Main.main(Main.scala)
Makefile:31: recipe for target 'anchored_membrane_component.tsv' failed
```

**Comment by cmungall** [comment]
I think this happens when we have a union expression in vars, e.g.

```
vars: 
  membrane: "'membrane' or 'side of membrane'"
```

**Comment by balhoff** [comment]
Is this what I should be running to check this? 

https://github.com/geneontology/go-ontology/blob/d760555055921d776b2f93f09ff47667f1b35841/src/design_patterns/Makefile#L30-L31
