### ISSUE TITLE
Weird exception for an (as of yet) unknown reason

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#339]
```
dosdp-tools query --ontology=mondo-edit.obo --catalog=catalog-v001.xml --reasoner=elk --obo-prefixes=true --batch-patterns="environmental_stimulus nuclear_subtype meningioma squamous_cell_carcinoma rhabdomyosarcoma y_linked specific_infectious_disease_by_location sarcoma inborn_metabolic_disrupts refractory disease_series_by_gene autosomal_dominant mucoepidermoid_carcinoma adenoma autoimmune chronic leiomyosarcoma infectious_disease_by_agent allergic_form_of_disease hemangioma rare_genetic small_cell_carcinoma infectious_inflammation leiomyoma congenital hereditary x_linked neoplasm_by_origin consequence_of_infectious_disease melanoma benign_neoplasm location syndromic inflammatory_disease_by_site specific_disease_by_dysfunctional_structure poisoning basis_in_disruption_of_process autosomal_recessive lipoma vectorBorneDisease neoplasm benign primary_infectious realized_in_response_to_environmental_exposure adenocarcinoma infantile dependence_on_substance acute idiopathic substance_abuse susceptibility_by_gene carcinoma lymphoma neuroendocrine_neoplasm childhood disease_by_dysfunctional_structure carcinoma_in_situ adenosquamous_carcinoma location_top cancer specific_disease_by_disrupted_process rare disease_series_by_gene_and_inheritance acquired neuroendocrine_neoplasm_grade1 disrupts_process adult inborn_metabolic juvenile malignant allergy autoimmune_inflammation postinfectious_disease mitochondrial_subtype specific_inflammatory_disease_by_site specific_infectious_disease_by_agent inherited_susceptibility genetic isolated" --template="../patterns/dosdp-patterns" --outfile="../patterns/data/matches/"
2021.07.01 11:33:37:186 [zio-def...] [ERROR] org.semanticweb.owlapi.utilities.Injector - No instantiation found for org.semanticweb.owlapi.model.OWLOntologyBuilder arg0
2021.07.01 11:33:37:208 [zio-def...] [ERROR] org.semanticweb.owlapi.utilities.Injector - Instantiation failed
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.semanticweb.owlapi.utilities.Injector.instantiate(Injector.java:364)
	at org.semanticweb.owlapi.utilities.Injector.lambda$load$5(Injector.java:297)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.semanticweb.owlapi.utilities.Injector.inject(Injector.java:209)
	at org.obolibrary.obo2owl.OwlStringTools.translate(OwlStringTools.java:113)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.trHeaderFrame(OWLAPIObo2Owl.java:557)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.tr(OWLAPIObo2Owl.java:371)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.convert(OWLAPIObo2Owl.java:319)
	at org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:95)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1303)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1243)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1143)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1097)
	at org.monarchinitiative.dosdp.Utilities$.$anonfun$loadOntology$10(Utilities.scala:37)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:490)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: value cannot be null at this stage
	at org.semanticweb.owlapi.util.OWLAPIPreconditions.verifyNotNull(OWLAPIPreconditions.java:61)
	at org.semanticweb.owlapi.util.OWLAPIPreconditions.verifyNotNull(OWLAPIPreconditions.java:40)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.<init>(OWLOntologyFactoryImpl.java:59)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.semanticweb.owlapi.utilities.Injector.instantiate(Injector.java:364)
	at org.semanticweb.owlapi.utilities.Injector.lambda$load$5(Injector.java:297)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.semanticweb.owlapi.utilities.Injector.inject(Injector.java:209)
	at org.obolibrary.obo2owl.OwlStringTools.translate(OwlStringTools.java:113)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.trHeaderFrame(OWLAPIObo2Owl.java:557)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.tr(OWLAPIObo2Owl.java:371)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.convert(OWLAPIObo2Owl.java:319)
	at org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:95)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1303)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1243)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1143)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1097)
	at org.monarchinitiative.dosdp.Utilities$.$anonfun$loadOntology$10(Utilities.scala:37)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:490)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

**Comment by matentzn** [comment]
Hmm this command has always worked. Weird, is it possible I didn't try this on Mondo since the last 0.17 release?

Works:

```
sh run.sh dosdp-tools query --ontology=mondo.owl --catalog=catalog-v001.xml --reasoner=elk --obo-prefixes=true --batch-patterns="specific_infectious_disease_by_location sarcoma" --template="../patterns/dosdp-patterns" --outfile="../patterns/data/matches/"
```

Does not work:

```
sh run.sh dosdp-tools query --ontology=mondo-edit.obo --catalog=catalog-v001.xml --reasoner=elk --obo-prefixes=true --batch-patterns="specific_infectious_disease_by_location sarcoma" --template="../patterns/dosdp-patterns" --outfile="../patterns/data/matches/"
```

You can replicate this by:

```
git clone https://github.com/monarch-initiative/mondo.git
cd mondo/src/ontology
sh run.sh dosdp-tools query --ontology=mondo-edit.obo --catalog=catalog-v001.xml --reasoner=elk --obo-prefixes=true --batch-patterns="specific_infectious_disease_by_location sarcoma" --template="../patterns/dosdp-patterns" --outfile="../patterns/data/matches/"
```

**Comment by balhoff** [comment]
I think this is an obscure OWL API OBO parser problem, not really specific to dosdp-tools.

**Comment by matentzn** [comment]
Just a bit odd that dosdp tools choked on it while robot did not! But low prio now, thanks for diagnosing.

**Comment by balhoff** [comment]
I still suspect it might be an OWL API version difference.
